"""Add AppWare table

Revision ID: f7c8d9e1a2b3
Revises: 1a31ce608336
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy import BigInteger


# revision identifiers, used by Alembic.
revision = 'f7c8d9e1a2b3'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'appware',
        sa.Column('id', BigInteger(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('view_count', BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引以提高查询性能
    op.create_index(op.f('ix_appware_name'), 'appware', ['name'], unique=False)
    op.create_index(op.f('ix_appware_status'), 'appware', ['status'], unique=False)
    op.create_index(op.f('ix_appware_is_active'), 'appware', ['is_active'], unique=False)
    op.create_index(op.f('ix_appware_is_deleted'), 'appware', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_appware_created_at'), 'appware', ['created_at'], unique=False)
    op.create_index(op.f('ix_appware_sort_order'), 'appware', ['sort_order'], unique=False)
    op.create_index(op.f('ix_appware_view_count'), 'appware', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appware_view_count'), table_name='appware')
    op.drop_index(op.f('ix_appware_sort_order'), table_name='appware')
    op.drop_index(op.f('ix_appware_created_at'), table_name='appware')
    op.drop_index(op.f('ix_appware_is_deleted'), table_name='appware')
    op.drop_index(op.f('ix_appware_is_active'), table_name='appware')
    op.drop_index(op.f('ix_appware_status'), table_name='appware')
    op.drop_index(op.f('ix_appware_name'), table_name='appware')
    op.drop_table('appware')
    # ### end Alembic commands ###